Config = {
    AllowedJobs = {
        ['police'] = true,
        ['ems'] = true,
    },
    CallsData = {
        ['CarFleeing'] = {
            code = 'CarFleeing',
            displayCode = 'CarFleeing',
            description = 'Vehicle seen at scene',
            recipientList = {['police'] = true},
            isImportant = false,
            isArea = true,
            blipSprite = 326,
            blipColor = 0,
            playSound = false,
            soundName = nil,
            priority = 1,
        },
        ['10-10'] = {
            code = '10-10',
            displayCode = '10-10',
            description = 'Fight in progress',
            recipientList = {['police'] = true},
            isImportant = false,
            isArea = false,
            blipSprite = 311,
            blipColor = 0,
            playSound = false,
            soundName = nil,
            priority = 1,
        },
        ['10-11'] = {
            code = '10-11',
            displayCode = '10-11',
            description = 'Deadly weapon',
            recipientList = {['police'] = true},
            isImportant = false,
            isArea = false,
            blipSprite = 154,
            blipColor = 0,
            playSound = false,
            soundName = nil,
            priority = 2,
        },
        ['10-13A'] = {
            code = '10-13A',
            displayCode = '10-13A',
            description = 'Officer down URGENT',
            recipientList = {['police'] = true, ['ems'] = true, ['doc'] = true},
            isImportant = true,
            isArea = false,
            blipSprite = 621,
            blipColor = 26,
            playSound = true,
            soundName = '10-1314',
            priority = 3,
        },
        ['10-14A'] = {
            code = '10-14A',
            displayCode = '10-14A',
            description = 'Medic down URGENT',
            recipientList = {['police'] = true, ['ems'] = true},
            isImportant = true,
            isArea = false,
            blipSprite = 621,
            blipColor = 35,
            playSound = true,
            soundName = '10-1314',
            priority = 3,
        },
        ['10-31A'] = {
            code = '10-31A',
            displayCode = '10-31A',
            description = 'Breaking and entering',
            recipientList = {['police'] = true},
            isImportant = false,
            isArea = false,
            blipSprite = 500,
            blipColor = 0,
            playSound = false,
            soundName = nil,
            priority = 2,
        },
        ['10-31B'] = {
            code = '10-31B',
            displayCode = '10-31B',
            description = 'Robbery with a deadly weapon',
            recipientList = {['police'] = true},
            isImportant = false,
            isArea = false,
            blipSprite = 458,
            blipColor = 0,
            playSound = false,
            soundName = nil,
            priority = 2,
        },
        ['10-45A'] = {
            code = '10-45A',
            displayCode = '10-45A',
            description = 'Animal Carcass at',
            recipientList = {['police'] = true},
            isImportant = false,
            isArea = false,
            blipSprite = 433,
            blipColor = 52,
            playSound = false,
            soundName = nil,
            priority = 2,
        },
        ['10-45B'] = {
            code = '10-45B',
            displayCode = '10-45B',
            description = 'Human Corpse at',
            recipientList = {['police'] = true},
            isImportant = false,
            isArea = false,
            blipSprite = 433,
            blipColor = 52,
            playSound = false,
            soundName = nil,
            priority = 2,
        },
        ['10-32'] = {
            code = '10-32',
            displayCode = '10-32',
            description = 'Person with firearm',
            recipientList = {['police'] = true},
            isImportant = false,
            isArea = false,
            blipSprite = 110,
            blipColor = 0,
            playSound = false,
            soundName = nil,
            priority = 2,
        },
        ['10-34'] = {
            code = '10-34',
            displayCode = '10-34',
            description = 'Drug sale',
            recipientList = {['police'] = true},
            isImportant = false,
            isArea = false,
            blipSprite = 140,
            blipColor = 0,
            playSound = false,
            soundName = nil,
            priority = 1,
        }
    }
}